#!/bin/bash
export LD_LIBRARY_PATH=$PREFIX/lib/
export CMAKE_LIBRARY_PATH=$PREFIX/lib/
export PATH=$PREFIX/bin:$PATH
export DYLD_LIBRARY_PATH=$PREFIX/lib:$PREFIX/lib/cyclus:$DYLD_LIBRARY_PATH

mkdir build;cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$PREFIX -DCYCLUS_ROOT_DIR=$PREFIX  -DCYCLOPTS_ROOT_DIR=$PREFIX -DCOIN_ROOT_DIR=$PREFIX -DBOOST_ROOT=$PREFIX -DBoost_NO_SYSTEM_PATHS=ON -DCMAKE_BUILD_TYPE=Release
make
make install
